services:
    simple_bus.message_logger:
        class: SimpleBus\SymfonyBridge\Logger\MessageLogger

    simple_bus.logging.events_middleware:
        class: SimpleBus\SymfonyBridge\Bus\Middleware\MessageLogger
        arguments:
            - @simple_bus.message_logger
            - event_bus
            - event
        tags:
            - {name: event_bus_middleware, priority: -1001}

    simple_bus.logging.command_executing_middleware:
        class: SimpleBus\SymfonyBridge\Bus\Middleware\MessageLogger
        arguments:
            - @simple_bus.message_logger
            - command_bus
            - executing
        tags:
            - {name: command_bus_middleware, priority: -999}

    simple_bus.logging.command_executed_middleware:
        class: SimpleBus\SymfonyBridge\Bus\Middleware\MessageLogger
        arguments:
            - @simple_bus.message_logger
            - command_bus
            - executed
        tags:
            - {name: command_bus_middleware, priority: -1001}

    simple_bus.logging.command_incoming_middleware:
        class: SimpleBus\SymfonyBridge\Bus\Middleware\MessageLogger
        arguments:
            - @simple_bus.message_logger
            - command_bus
            - incoming
        tags:
            - {name: command_bus_middleware, priority: 1001}

    simple_bus.data_collector:
        class: SimpleBus\SymfonyBridge\DataCollector\MessageBusDataCollector
        arguments:
            - @simple_bus.message_logger
        tags:
            - { name: data_collector, template: "SimpleBusEventBusBundle::collector.html.twig", id: "simple_bus"}
