services:
    simple_bus.message_logger:
        class: SimpleBus\SymfonyBridge\Logger\MessageLogger

    simple_bus.profiler.bus_registry:
        class: SimpleBus\SymfonyBridge\Bus\BusRegistry

    simple_bus.logging.profiler_middleware.abstract:
        class: SimpleBus\SymfonyBridge\Bus\Middleware\MessageLogger
        abstract: true
        public: false
        arguments:
            - @simple_bus.message_logger
            - ~

    simple_bus.data_collector:
        class: SimpleBus\SymfonyBridge\DataCollector\MessageBusDataCollector
        arguments:
            - @simple_bus.message_logger
            - @simple_bus.profiler.bus_registry
        tags:
            - { name: data_collector, template: "SimpleBusEventBusBundle::collector.html.twig", id: "simple_bus"}
